Letux-user.deb: check if user is already installed
Signed-off-by: H. Nikolaus Schaller <hns@goldelico.com>

diff --git a/packages/letux-user/letux-user.postinst b/packages/letux-user/letux-user.postinst
--- a/packages/letux-user/letux-user.postinst
+++ b/packages/letux-user/letux-user.postinst
@@ -19,10 +19,15 @@ set -e
 
 case "$1" in
     configure)
-	adduser --uid 500 --disabled-login --gecos '' letux || { sync; echo "### adduser failed"; exit 1; }
-	(echo letux; echo letux; echo letux) | passwd letux
-	adduser letux sudo # allow to su
-	echo "+++ user letux:letux added +++"    
+	if id letux 2>/dev/null
+	then
+		echo "+++ user letux:letux exists +++"
+	else
+		adduser --uid 500 --disabled-login --gecos '' letux || { sync; echo "### adduser failed"; exit 1; }
+		(echo letux; echo letux; echo letux) | passwd letux
+		adduser letux sudo # allow to su
+		echo "+++ user letux:letux added +++"
+	fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
