letux-usbmount: try to detect improperly decoded LABEL
Signed-off-by: H. Nikolaus Schaller <hns@goldelico.com>

diff --git a/packages/letux-usbmount/usr/share/usbmount/usbmount b/packages/letux-usbmount/usr/share/usbmount/usbmount
--- a/packages/letux-usbmount/usr/share/usbmount/usbmount
+++ b/packages/letux-usbmount/usr/share/usbmount/usbmount
@@ -140,6 +140,9 @@ if [ "$1" = add ]; then
 
     if [ "$LABEL" ]
     then # create dynamic mountpoint name
+case "$LABEL" in
+	*/* ) log err "invalid label: $LABEL"; log err "devinfo: $DEVINFO"; exit 1;;
+esac
 	mount="$MOUNTDIR/$LABEL"
 # echo "$0: mounting $LABEL as $mount" >/dev/console
 	if grep -q "^[^ ][^ ]* *$mount " /proc/mounts
