letux-httpd: make postinst/prerm install macports apache and php on Darwin host
Signed-off-by: H. Nikolaus Schaller <hns@goldelico.com>

diff --git a/letux-httpd/letux-httpd.postinst b/letux-httpd/letux-httpd.postinst
--- a/letux-httpd/letux-httpd.postinst
+++ b/letux-httpd/letux-httpd.postinst
@@ -1,5 +1,5 @@
 #! /bin/sh
-# postinst script for rootfs-beta
+# postinst script for letux-httpd
 #
 # see: dh_installdeb(1)
 
@@ -17,6 +17,133 @@ set -e
 # the debian-policy package
 #
 
+function install_darwin_php {
+	PHPVERSIONS=84	# 5.6, 5.7, 8.1, 8.2 and 8.3 are broken
+
+	for PHP in $PHPVERSIONS
+	do
+		echo +++ install packages for PHP$PHP support +++ >&2
+
+		PACKAGES="php$PHP-apache2handler php$PHP-posix php$PHP-opcache php$PHP-openssl"
+# some of these may be optional and should be installed by letux-amp or quantumstep-webserver
+# abgleichen was Linux als Extensions geladen hat!
+#		PACKAGES+="  php$PHP-mysql"	# => letux-amp
+#		PACKAGES+="  php$PHP-mbstring php$PHP-zip php$PHP-intl php$PHP-iconv php$PHP-pcntl php$PHP-mysql php$PHP-gd php$PHP-curl php$PHP-imagick php$PHP-sqlite gnutar"	# => quantumstep-webserver
+		sudo port -N install $PACKAGES
+
+		echo +++ php setup +++ >&2
+#cp /opt/local/etc/php$PHP/php.ini-development /opt/local/etc/php$PHP/php.ini
+		sudo cp /opt/local/etc/php$PHP/php.ini-production /opt/local/etc/php$PHP/php.ini
+
+		sudo sed -i.bak -e 's|memory_limit = .*|memory_limit = 512M|g' \
+      		  	-e 's|;pcre.jit=1|pcre.jit=0|g' \
+		/opt/local/etc/php$PHP/php.ini
+
+		echo +++ opcache disabled +++ >&2
+: *disabled* cat <<END >/dev/null
+enable opcache
+https://www.scalingphpbook.com/blog/2014/02/14/best-zend-opcache-settings.html
+opcache.revalidate_freq=0
+opcache.validate_timestamps=0 (comment this out in your dev environment)
+opcache.max_accelerated_files=7963
+opcache.memory_consumption=192
+opcache.interned_strings_buffer=16
+opcache.fast_shutdown=1
+www:www.modiblast.de hns$ fgrep opcache /opt/local/etc/php73/php.ini
+[opcache]
+;opcache.enable=1
+;opcache.enable_cli=0
+;opcache.memory_consumption=128
+;opcache.interned_strings_buffer=8
+;opcache.max_accelerated_files=10000
+;opcache.max_wasted_percentage=5
+;opcache.use_cwd=1
+;opcache.validate_timestamps=1
+;opcache.revalidate_freq=2
+;opcache.revalidate_path=0
+;opcache.save_comments=1
+;opcache.enable_file_override=0
+;opcache.optimization_level=0x7FFFBFFF
+;opcache.dups_fix=0
+;opcache.blacklist_filename=
+;opcache.max_file_size=0
+;opcache.consistency_checks=0
+;opcache.force_restart_timeout=180
+;opcache.error_log=
+;opcache.log_verbosity_level=1
+;opcache.preferred_memory_model=
+;opcache.protect_memory=0
+;opcache.restrict_api=
+;opcache.mmap_base=
+;opcache.file_cache=
+;opcache.file_cache_only=0
+;opcache.file_cache_consistency_checks=1
+; Implies opcache.file_cache_only=1 for a certain process that failed to
+;opcache.file_cache_fallback=1
+;opcache.huge_code_pages=1
+;opcache.validate_permission=0
+;opcache.validate_root=0
+;opcache.opt_debug_level=0
+www:www.modiblast.de hns$
+END
+
+		echo +++ choose php$PHP for Apache through apxs +++ >&2
+		(
+			cd /opt/local/lib/apache2/modules
+			case "$PHP" in
+				5* ) sudo /opt/local/bin/apxs -a -e -n php5 mod_php$PHP.so;;
+				7* ) sudo /opt/local/bin/apxs -a -e -n php7 mod_php$PHP.so;;
+				8* ) sudo /opt/local/bin/apxs -a -e -n php mod_php$PHP.so;;	# name changed: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12249
+			esac
+		)
+
+		echo +++ choose php$PHP for shell +++ >&2
+		sudo port -N select --set php php$PHP
+
+		echo +++ enable php.conf for PHP$PHP httpd.conf +++ >&2
+		if ! fgrep "Include etc/apache2/extra/mod_php$PHP.conf" /opt/local/etc/apache2/httpd.conf
+		then
+			sudo sh -c "echo Include etc/apache2/extra/mod_php$PHP.conf >>/opt/local/etc/apache2/httpd.conf"
+		fi
+	done
+}
+
+function install_darwin_apache {
+	# tweak httpd-conf
+	echo +++  stop running apache +++ >&2
+	echo may ask for root password: >&2
+	# echo +++ restore httpd.conf +++ >&2
+	sudo cp /opt/local/etc/apache2/httpd.conf.orig /opt/local/etc/apache2/httpd.conf
+	sudo apachectl -k stop	# to be sure...
+	sudo port -N unload apache2 || true	# may fail on first install
+	sleep 5	# may need some time to free the socket
+	[ "$DOCROOT" ] || export DOCROOT=/usr/local/QuantumSTEP/var/www/html
+	[ "$PORT" ] || export PORT=4999
+	echo +++ make Apache2 a server for http://localhost:$PORT +++ >&2
+	# FIXME: should we run as _www:_www?
+	USER=$(stat -f '%Su' $DOCROOT)
+	GROUP=$(stat -f '%Sg' $DOCROOT)
+	# echo user "$USER" "$GROUP" >&2
+	sudo sed -i.bak -e "s|Listen .*|Listen 127.0.0.1:$PORT|g" \
+		-e "s|DirectoryIndex index.html|DirectoryIndex index.php index.html|g" \
+		-e "s|DocumentRoot .*|DocumentRoot \"$DOCROOT\"|g" \
+		-e "/DocumentRoot .*/,/<\/Directory>/s|<Directory .*>|<Directory \"$DOCROOT\">|g" \
+		-e "/DocumentRoot .*/,/<\/Directory>/s|AllowOverride None|AllowOverride All|g" \
+		-e "s|User .*|User $USER|g" \
+		-e "s|Group .*|Group $GROUP|g" \
+		-e "s|#LoadModule rewrite_module lib/apache2/modules/mod_rewrite.so|LoadModule rewrite_module lib/apache2/modules/mod_rewrite.so|g" \
+		-e "s|ServerRoot .*|ServerRoot "\/opt\/local"|g" \
+		-e "s|#*ServerName .*|ServerName \"localhost:$PORT\"|g" \
+	/opt/local/etc/apache2/httpd.conf
+	install_darwin_php
+	echo +++ checking config +++ >&2
+	/opt/local/sbin/apachectl -t >&2
+	sudo port -N load apache2 >&2
+	sudo apachectl -k start
+	echo +++ to restart the httpd +++ >&2
+	echo "  sudo apachectl -k restart" >&2
+}
+
 case "$1" in
     configure)
 	# start httpd
@@ -28,38 +155,7 @@ case "$1" in
 			echo service apache2 restart >&2
 			;;
 		Darwin )
-			# tweak httpd-conf
-			echo ">>" stop running apache >&2
-			sudo apachectl -k stop	# to be sure...
-			sudo port -N unload apache2 || true	# may fail on first install
-			[ "$DOCROOT" ] || export DOCROOT=/usr/local/QuantumSTEP/var/www/html
-			[ "$PORT" ] || export PORT=4999
-			echo ">>" restore httpd.conf >&2
-			sudo cp /opt/local/etc/apache2/httpd.conf.orig /opt/local/etc/apache2/httpd.conf
-			echo ">>" make Apache2 a server >&2
-			echo may ask for root password: >&2
-			# FIXME: should we run as _www:_www?
-			USER=$(stat -f '%Su' $DOCROOT)
-			GROUP=$(stat -f '%Sg' $DOCROOT)
-			# echo user "$USER" "$GROUP" >&2
-			sudo sed -i.bak -e "s|Listen .*|Listen 127.0.0.1:$PORT|g" \
-				-e "s|DirectoryIndex index.html|DirectoryIndex index.php index.html|g" \
-				-e "s|DocumentRoot .*|DocumentRoot \"$DOCROOT\"|g" \
-				-e "/DocumentRoot .*/,/<\/Directory>/s|<Directory .*>|<Directory \"$DOCROOT\">|g" \
-				-e "/DocumentRoot .*/,/<\/Directory>/s|AllowOverride None|AllowOverride All|g" \
-				-e "s|User .*|User $USER|g" \
-				-e "s|Group .*|Group $GROUP|g" \
-				-e "s|#LoadModule rewrite_module lib/apache2/modules/mod_rewrite.so|LoadModule rewrite_module lib/apache2/modules/mod_rewrite.so|g" \
-				-e "s|ServerRoot .*|ServerRoot "\/opt\/local"|g" \
-				-e "s|#*ServerName .*|ServerName \"localhost:$PORT\"|g" \
-			/opt/local/etc/apache2/httpd.conf
-			echo "checking config" >&2
-			/opt/local/sbin/apachectl -t >&2
-			# to show /usr/local/QuantumSTEP/var/www/html
-			sudo port -N load apache2 >&2
-			sudo apachectl -k start
-			echo "to restart the httpd for http://localhost:$PORT" >&2
-			"sudo apachectl -k restart      # to be sure" >&2	# to be sure...
+			install_darwin_apache
 			;;
 		* )
 			echo unknown OS: $(uname -a) >&2
diff --git a/letux-httpd/letux-httpd.prerm b/letux-httpd/letux-httpd.prerm
--- a/letux-httpd/letux-httpd.prerm
+++ b/letux-httpd/letux-httpd.prerm
@@ -1,5 +1,5 @@
 #! /bin/sh
-# prerm script for linux-image-letux
+# prerm script for letux-amp
 #
 # see: dh_installdeb(1)
 
@@ -20,6 +20,27 @@ set -e
 case "$1" in
     remove)
 	# stop httpd
+	case "$(uname -s)" in
+		Linux )
+			# will be stopped elsewhere
+			;;
+		Darwin )
+			echo ">>" stop running apache >&2
+			echo may ask for root password: >&2
+			sudo apachectl -k stop
+			sudo port -N unload apache2 || true	# may fail
+			PHPVERSIONS=84	# 5.6, 5.7, 8.1, 8.2 and 8.3 are broken
+
+			for PHP in $PHPVERSIONS
+			do
+				PACKAGES="php$PHP-apache2handler php$PHP-posix php$PHP-opcache php$PHP-openssl"
+				sudo port -N uninstall $PACKAGES
+			done
+			;;
+		* )
+			echo unknown OS: $(uname -a) >&2
+			;;
+	esac
     ;;
 
     upgrade|deconfigure)
