update preinst and prerm for purism-sources-list.deb
Signed-off-by: H. Nikolaus Schaller <hns@goldelico.com>

diff --git a/packages/purism-sources-list/purism-sources-list.preinst b/packages/purism-sources-list/purism-sources-list.preinst
--- a/packages/purism-sources-list/purism-sources-list.preinst
+++ b/packages/purism-sources-list/purism-sources-list.preinst
@@ -18,6 +18,13 @@ case "$1" in
 	echo "deb https://ci.puri.sm/ scratch librem5" >/etc/apt/sources.list.d/ci-puri-sm.list
 	/usr/bin/wget -O - https://ci.puri.sm/ci-repo.key | apt-key add -
 
+	adduser --uid 1000 --disabled-login --gecos '' purism || { sync; echo "### adduser failed"; exit 1; }
+	echo 123456 | sed 'p' | passwd purism
+	adduser purism sudo # allow to su
+	adduser purism audio
+	adduser purism video
+	echo "+++ user purism:123456 added +++"
+
 	echo "***********************************************" >&2
 	echo "*                                             *" >&2
 	echo "* We have updated the /etc/apt/sources.list.d *" >&2
